<h1>Algorithmic Trading Course</h1>

<h3>SECTION 01: Algorithmic Trading Basics</h3>

Algorithmic trading means using computers to mae invstment decisions.

There are many different types of algorithmic trading. The main difference is their spee of execution.

Here are some of the main players in the algorthmic trading landscape:
- Renaissance Technologies: $165Bin AUM
- AQR Capital Management: $61B in AUM
- Citadel Securities: $32B in AUM

<h4> The algorithmic Trading Process:</h4>
The process of running a quantitative investing strategy can be broken down into the following steps:<br>

1. Collect Data
2. Develope a hypohesis for a strategy
3. Backtest that strategy
4. Implement the strategy in production

<h3>SECTION 02: API Basics and Course Configuration</h3>

<h4> What is an API? </h4>
An API is an Application Programing Interface. It allow us to interact with someone else's software.<br>
We are going to use IEX Cloud API to access database of financial data.<br><br/>
In this course will be using the GET request to gather data from the IEX Cloud API.

Other API Functionality:
- POST: Adds data to the database exposed by the API. (Create only)
- PUT: Adds and verviewrites data in the database exposed by the API. (Create or replace)
- DELETE: Deletes data from the API's database.

----------

### PROJECT 01 - Equal-Weight S&P 500 Screener

The S&P 500 is the world's most popular stock market index.<br>
Many investment funds are benchmarked to the S&P 500. This means that they seek to replicate the performance of this index by owning all stocks that are held in the index.<br>
The S&P covers the 500 largest companies of United States.

In the first project you will build an alternative version of the S&P 500 that assigns the same wheight to each company.<br>
The goal of this project is to create a Python script that accepts the value on your portfolio and tell you how many shares of each S&P 500 constituent you should purchase to get an equal-weight version of the index fund.

<h4>Importing libraries</h4>

In [22]:
import numpy as np
import pandas as pd 
import requests 
import xlsxwriter
import math

<h4> Importing Our List of Stocks</h4>
The stock in S&P 500 change over time, they are re-balanced.So in the real world you would connect to the Standard and Poors provider and pull their real-time database.<br></br>

For now we are going to use this static version of S&P. [Click this link to download them now](http://nickmccullum.com/algorithmic-trading-python/sp_500_stocks.csv).

In [23]:
stocks = pd.read_csv('https://raw.githubusercontent.com/GustavoJannuzzi/Quant_projects_for_UPQuants/main/sp_500_stocks.csv')

<h4>Acquiring an API Token</h4>

API tokens an secret information must be stored in a `secrets.py` file that doesn't get pushed to your local Git repository. 
For now we are going to use a sandbox mode, that's kinda like a game mode. It will make sure that all off ur API calls work, but it doesn't actually return real time financial data. It will return a random financial data. 

[Click here](http://nickmccullum.com/algorithmic-trading-python/secrets.py) to download your `secrets.py` file. Move the file into the same directory as this Jupyter Notebook before proceeding.

In [24]:
from secrets import IEX_CLOUD_API_TOKEN

<h4> Making the first API call</h4>
We 'll need the following information from the API:

- market capitalization for each stock
- price of each stock

In [25]:
symbol = 'AAPL'
api_url = f'https://sandbox.iexapis.com/stable/stock/{symbol}/quote?token={IEX_CLOUD_API_TOKEN}'
data = requests.get(api_url).json()
data

{'avgTotalVolume': 71055332,
 'calculationPrice': 'close',
 'change': 2.98,
 'changePercent': 0.01946,
 'close': 163.8,
 'closeSource': 'oilfcifa',
 'closeTime': 1702172494285,
 'companyName': 'Apple Inc',
 'currency': 'USD',
 'delayedPrice': 159.67,
 'delayedPriceTime': 1675637994211,
 'extendedChange': 0.15,
 'extendedChangePercent': 0.00098,
 'extendedPrice': 157.69,
 'extendedPriceTime': 1692824155824,
 'high': 163.8,
 'highSource': 'yrcaemdep t1 e nidlue5i',
 'highTime': 1730747242237,
 'iexAskPrice': None,
 'iexAskSize': None,
 'iexBidPrice': None,
 'iexBidSize': None,
 'iexClose': 161.24,
 'iexCloseTime': 1713066220917,
 'iexLastUpdated': None,
 'iexMarketPercent': None,
 'iexOpen': 160.54,
 'iexOpenTime': 1693642099610,
 'iexRealtimePrice': None,
 'iexRealtimeSize': None,
 'iexVolume': None,
 'lastTradeTime': 1678716646456,
 'latestPrice': 159.22,
 'latestSource': 'Close',
 'latestTime': 'September 9, 2022',
 'latestUpdate': 1704073367916,
 'latestVolume': 70279229,
 'low': 156.67,
 'lowSource': 'n51prm eitc deye adeuli',
 'lowTime': 1701245720735,
 'marketCap': 2565999627586,
 'oddLotDelayedPrice': 159.78,
 'oddLotDelayedPriceTime': 1666464880479,
 'open': 156.67,
 'openTime': 1667405222815,
 'openSource': 'alfcifio',
 'peRatio': 26.72,
 'previousClose': 159.15,
 'previousVolume': 87917130,
 'primaryExchange': 'NQDAAS',
 'symbol': 'AAPL',
 'volume': 68185467,
 'week52High': 182.91,
 'week52Low': 130.61,
 'ytdChange': -0.09487558831893293,
 'isUSMarketOpen': False}

<h4>Parsing Our API call</h4>
The API call that we executed in the last code block contains all the information required to build our equal-wieght S&P<br>

In [26]:
price = data['latestPrice']
market_cap = data['marketCap']

<h4>Adding stock data to Pandas DF</h4>

In [27]:
my_columns = ['Ticker', 'Stock Price', 'Market Capitalization', 'Number of Shares to buy']
final_dataframe = pd.DataFrame(columns = my_columns)
final_dataframe

Empty DataFrame
Columns: [Ticker, Stock Price, Market Capitalization, Number of Shares to buy]
Index: []

In [28]:
final_dataframe = final_dataframe.append(
                                        pd.Series(['AAPL', 
                                                   data['latestPrice'], 
                                                   data['marketCap'], 
                                                   'N/A'], 
                                                  index = my_columns), 
                                        ignore_index = True)
final_dataframe

  Ticker  Stock Price Market Capitalization Number of Shares to buy
0   AAPL       159.22         2565999627586                     N/A

<h4> Looping throught the ticker in our list of stocks</h4>
Now we'll feed de dataframe calling all the stock in our list of stocks.

In [ ]:
final_dataframe = pd.DataFrame(columns = my_columns)
for stock in stocks['Ticker']:
    api_url = f'https://sandbox.iexapis.com/stable/stock/{stock}/quote?token={IEX_CLOUD_API_TOKEN}'
    data = requests.get(api_url).json()
    final_dataframe = final_dataframe.append(
                                        pd.Series([stock, 
                                                   data['latestPrice'], 
                                                   data['marketCap'], 
                                                   'N/A'], 
                                                  index = my_columns), 
                                        ignore_index = True)

In [ ]:
final_dataframe

    Ticker  Stock Price Market Capitalization Number of Shares to buy
0     AAPL       158.42         2599979531580                     N/A
1     AAPL       157.59         2649768942842                     N/A
2     AAPL       161.63         2636339965222                     N/A
3     AAPL       161.23         2611884687235                     N/A
4     AAPL       164.45         2627778455011                     N/A
..     ...          ...                   ...                     ...
500   AAPL       160.29         2646209054640                     N/A
501   AAPL       162.86         2548908850147                     N/A
502   AAPL       164.23         2582595834262                     N/A
503   AAPL       158.53         2644361368810                     N/A
504   AAPL       158.02         2565413673596                     N/A

[505 rows x 4 columns]

<h4>Using Batch API Calls to improve Performance</h4>

Batch API calls have better perfomance. This is because HTTP requests are one of the slowest componetsof a script.<br></br>
IEX Clous limits thei batch API calls to 100 tickers per request. Still, this reduce the number of API calls. So we will split our list of stocks into groups of 100 and then make a batch API call for it.

In [40]:
#function to split de data into sub-lists
def chunks(lst, n):
    for i in range(0, len(lst), n):
        yield lst[i:i + n]

In [41]:
symbol_groups = list(chunks(stocks['Ticker'], 100))
symbol_strings = []
for i in range(0, len(symbol_groups)):
    symbol_strings.append(','.join(symbol_groups[i]))
    print(symbol_strings[i])

A,AAL,AAP,AAPL,ABBV,ABC,ABMD,ABT,ACN,ADBE,ADI,ADM,ADP,ADSK,AEE,AEP,AES,AFL,AIG,AIV,AIZ,AJG,AKAM,ALB,ALGN,ALK,ALL,ALLE,ALXN,AMAT,AMCR,AMD,AME,AMGN,AMP,AMT,AMZN,ANET,ANSS,ANTM,AON,AOS,APA,APD,APH,APTV,ARE,ATO,ATVI,AVB,AVGO,AVY,AWK,AXP,AZO,BA,BAC,BAX,BBY,BDX,BEN,BF.B,BIIB,BIO,BK,BKNG,BKR,BLK,BLL,BMY,BR,BRK.B,BSX,BWA,BXP,C,CAG,CAH,CARR,CAT,CB,CBOE,CBRE,CCI,CCL,CDNS,CDW,CE,CERN,CF,CFG,CHD,CHRW,CHTR,CI,CINF,CL,CLX,CMA,CMCSA
CME,CMG,CMI,CMS,CNC,CNP,COF,COG,COO,COP,COST,COTY,CPB,CPRT,CRM,CSCO,CSX,CTAS,CTL,CTSH,CTVA,CTXS,CVS,CVX,CXO,D,DAL,DD,DE,DFS,DG,DGX,DHI,DHR,DIS,DISCA,DISCK,DISH,DLR,DLTR,DOV,DOW,DPZ,DRE,DRI,DTE,DUK,DVA,DVN,DXC,DXCM,EA,EBAY,ECL,ED,EFX,EIX,EL,EMN,EMR,EOG,EQIX,EQR,ES,ESS,ETFC,ETN,ETR,EVRG,EW,EXC,EXPD,EXPE,EXR,F,FANG,FAST,FB,FBHS,FCX,FDX,FE,FFIV,FIS,FISV,FITB,FLIR,FLS,FLT,FMC,FOX,FOXA,FRC,FRT,FTI,FTNT,FTV,GD,GE,GILD
GIS,GL,GLW,GM,GOOG,GOOGL,GPC,GPN,GPS,GRMN,GS,GWW,HAL,HAS,HBAN,HBI,HCA,HD,HES,HFC,HIG,HII,HLT,HOLX,HON,HPE,HPQ,HRB,HRL,HSIC,HST,HSY,HUM,HWM,IBM,ICE,IDXX,IEX,IFF,ILMN,INCY,INFO,INTC,INTU,IP,IPG,IPGP,IQV,IR,IRM,ISRG,IT,ITW,IVZ,J,JBHT,JCI,JKHY,JNJ,JNPR,JPM,K,KEY,KEYS,KHC,KIM,KLAC,KMB,KMI,KMX,KO,KR,KSS,KSU,L,LB,LDOS,LEG,LEN,LH,LHX,LIN,LKQ,LLY,LMT,LNC,LNT,LOW,LRCX,LUV,LVS,LW,LYB,LYV,MA,MAA,MAR,MAS,MCD,MCHP
MCK,MCO,MDLZ,MDT,MET,MGM,MHK,MKC,MKTX,MLM,MMC,MMM,MNST,MO,MOS,MPC,MRK,MRO,MS,MSCI,MSFT,MSI,MTB,MTD,MU,MXIM,MYL,NBL,NCLH,NDAQ,NEE,NEM,NFLX,NI,NKE,NLOK,NLSN,NOC,NOV,NOW,NRG,NSC,NTAP,NTRS,NUE,NVDA,NVR,NWL,NWS,NWSA,O,ODFL,OKE,OMC,ORCL,ORLY,OTIS,OXY,PAYC,PAYX,PBCT,PCAR,PEAK,PEG,PEP,PFE,PFG,PG,PGR,PH,PHM,PKG,PKI,PLD,PM,PNC,PNR,PNW,PPG,PPL,PRGO,PRU,PSA,PSX,PVH,PWR,PXD,PYPL,QCOM,QRVO,RCL,RE,REG,REGN,RF,RHI,RJF,RL,RMD,ROK
ROL,ROP,ROST,RSG,RTX,SBAC,SBUX,SCHW,SEE,SHW,SIVB,SJM,SLB,SLG,SNA,SNPS,SO,SPG,SPGI,SRE,STE,STT,STX,STZ,SWK,SWKS,SYF,SYK,SYY,T,TAP,TDG,TDY,TEL,TFC,TFX,TGT,TIF,TJX,TMO,TMUS,TPR,TROW,TRV,TSCO,TSN,TT,TTWO,TWTR,TXN,TXT,TYL,UA,UAA,UAL,UDR,UHS,ULTA,UNH,UNM,UNP,UPS,URI,USB,V,VAR,VFC,VIAC,VLO,VMC,VNO,VRSK,VRSN,VRTX,VTR,VZ,WAB,WAT,WBA,WDC,WEC,WELL,WFC,WHR,WLTW,WM,WMB,WMT,WRB,WRK,WST,WU,WY,WYNN,XEL,XLNX,XOM,XRAY,XRX,XYL
YUM,ZBH,ZBRA,ZION,ZTS

<h4>Calculating the Number of share to buy</h4>

<h4>Formating our excel output</h4>

### PROJECT 02 - Quantitative Momentum Screener

<h3> Momentum Investing - Overview</h3>
Momentum investing significa investir em ativos que mais tenham aumentado seu valor.</br>
Considere este exemplo para entender melhor:<br>
Imagine que você tenha que escolher entre investir em duas ações que tiveram o seguinte resultado no ultimo ano:

- Apple(APPL): 35%
- Microsoft (MSFT): 20%

A momentum investing strategy iria sugerir investir em Apple por causa de seu retorno anual mais alto. <br>
Existem muitas outras nuancias nesta estratégia.

For this project we're going to build an investing strategy that selects the 50 stocks with the highest price momentum. From there, we will calculate recommended trades for an equal-weight portfolio of these 50 stocks

In [4]:
# Import library
import numpy as np
import pandas as pd
import requests
import math
from scipy import stats
import xlsxwriter

<h4> Importing our list of stocks </h4>

In [5]:
stocks = pd.read_csv('sp_500_stocks.csv')
from secrets import IEX_CLOUD_API_TOKEN

<h4> Making first API Call </h4>
Making the first version of momentum screener!<br>
We need to get one-year price returns for each stock in the universe. Like this...

In [6]:
symbol = 'AAPL'
api_url = f'https://sandbox.iexapis.com/stable/stock/{symbol}/stats?token={IEX_CLOUD_API_TOKEN}'
data = requests.get(api_url).json()
data

{'companyName': 'Apple Inc',
 'marketcap': 2374383112587,
 'week52high': 190.21,
 'week52low': 133.85,
 'week52highSplitAdjustOnly': 190.83,
 'week52lowSplitAdjustOnly': 132.35,
 'week52change': 0.013108599035769719,
 'sharesOutstanding': 16261580876,
 'float': 0,
 'avg10Volume': 105945027,
 'avg30Volume': 101568614,
 'day200MovingAvg': 156.59,
 'day50MovingAvg': 167.28,
 'employees': 152240,
 'ttmEPS': 6.05,
 'ttmDividendRate': 0.9391951031543626,
 'dividendYield': 0.006343858134269664,
 'nextDividendDate': '',
 'exDividendDate': '2022-07-22',
 'nextEarningsDate': '2022-10-20',
 'peRatio': 23.85130410573856,
 'beta': 1.244494370378841,
 'maxChangePercent': 54.51787414858666,
 'year5ChangePercent': 2.919861830332222,
 'year2ChangePercent': 0.2770646566217231,
 'year1ChangePercent': 0.003182546529075861,
 'ytdChangePercent': -0.19495798745147,
 'month6ChangePercent': -0.2018415543452058,
 'month3ChangePercent': 0.02561940424732087,
 'month1ChangePercent': -0.12257040646285987,
 'day30ChangePercent': -0.10461774647219294,
 'day5ChangePercent': -0.0693140360807732}

<h4> Parsing our API Call </h4>

In [7]:
data['year1ChangePercent']

0.003182546529075861

<h4>Executing a Bacth API Call and Building the DF</h4>

It contains a function called chunks that we can use to divide our list of securities into groups of 100.

In [8]:
# Function sourced from 
# https://stackoverflow.com/questions/312443/how-do-you-split-a-list-into-evenly-sized-chunks
def chunks(lst, n):
    """Yield successive n-sized chunks from lst."""
    for i in range(0, len(lst), n):
        yield lst[i:i + n]   
        
symbol_groups = list(chunks(stocks['Ticker'], 100))
symbol_strings = []
for i in range(0, len(symbol_groups)):
    symbol_strings.append(','.join(symbol_groups[i]))
#     print(symbol_strings[i])

my_columns = ['Ticker', 'Price', 'One-Year Price Return', 'Number of Shares to Buy']

In [9]:
symbol_strings
#alguns ativos precisaram ser removidos

['A,AAL,AAP,AAPL,ABBV,ABC,ABMD,ABT,ACN,ADBE,ADI,ADM,ADP,ADSK,AEE,AEP,AES,AFL,AIG,AIV,AIZ,AJG,AKAM,ALB,ALGN,ALK,ALL,ALLE,ALXN,AMAT,AMCR,AMD,AME,AMGN,AMP,AMT,AMZN,ANET,ANSS,ANTM,AON,AOS,APA,APD,APH,APTV,ARE,ATO,ATVI,AVB,AVGO,AVY,AWK,AXP,AZO,BA,BAC,BAX,BBY,BDX,BEN,BF.B,BIIB,BIO,BK,BKNG,BKR,BLK,BLL,BMY,BR,BRK.B,BSX,BWA,BXP,C,CAG,CAH,CARR,CAT,CB,CBOE,CBRE,CCI,CCL,CDNS,CDW,CE,CERN,CF,CFG,CHD,CHRW,CHTR,CI,CINF,CL,CLX,CMA,CMCSA',
 'CME,CMG,CMI,CMS,CNC,CNP,COF,COG,COO,COP,COST,COTY,CPB,CPRT,CRM,CSCO,CSX,CTAS,CTL,CTSH,CTVA,CTXS,CVS,CVX,CXO,D,DAL,DD,DE,DFS,DG,DGX,DHI,DHR,DIS,DISCA,DISCK,DISH,DLR,DLTR,DOV,DOW,DPZ,DRE,DRI,DTE,DUK,DVA,DVN,DXC,DXCM,EA,EBAY,ECL,ED,EFX,EIX,EL,EMN,EMR,EOG,EQIX,EQR,ES,ESS,ETFC,ETN,ETR,EVRG,EW,EXC,EXPD,EXPE,EXR,F,FANG,FAST,FB,FBHS,FCX,FDX,FE,FFIV,FIS,FISV,FITB,FLIR,FLS,FLT,FMC,FOX,FOXA,FRC,FRT,FTI,FTNT,FTV,GD,GE,GILD',
 'GIS,GL,GLW,GM,GOOG,GOOGL,GPC,GPN,GPS,GRMN,GS,GWW,HAL,HAS,HBAN,HBI,HCA,HD,HES,HFC,HIG,HII,HLT,HOLX,HON,HPE,HPQ,HRB,HRL,HSIC,HST,HSY,HUM,HWM,IBM,ICE,IDXX,IEX,IFF,ILMN,INCY,INFO,INTC,INTU,IP,IPG,IPGP,IQV,IR,IRM,ISRG,IT,ITW,IVZ,J,JBHT,JCI,JKHY,JNJ,JNPR,JPM,K,KEY,KEYS,KHC,KIM,KLAC,KMB,KMI,KMX,KO,KR,KSS,KSU,L,LB,LDOS,LEG,LEN,LH,LHX,LIN,LKQ,LLY,LMT,LNC,LNT,LOW,LRCX,LUV,LVS,LW,LYB,LYV,MA,MAA,MAR,MAS,MCD,MCHP',
 'MCK,MCO,MDLZ,MDT,MET,MGM,MHK,MKC,MKTX,MLM,MMC,MMM,MNST,MO,MOS,MPC,MRK,MRO,MS,MSCI,MSFT,MSI,MTB,MTD,MU,MXIM,MYL,NBL,NCLH,NDAQ,NEE,NEM,NFLX,NI,NKE,NLOK,NLSN,NOC,NOV,NOW,NRG,NSC,NTAP,NTRS,NUE,NVDA,NVR,NWL,NWS,NWSA,O,ODFL,OKE,OMC,ORCL,ORLY,OTIS,OXY,PAYC,PAYX,PBCT,PCAR,PEAK,PEG,PEP,PFE,PFG,PG,PGR,PH,PHM,PKG,PKI,PLD,PM,PNC,PNR,PNW,PPG,PPL,PRGO,PRU,PSA,PSX,PVH,PWR,PXD,PYPL,QCOM,QRVO,RCL,RE,REG,REGN,RF,RHI,RJF,RL,RMD,ROK',
 'ROL,ROP,ROST,RSG,RTX,SBAC,SBUX,SCHW,SEE,SHW,SIVB,SJM,SLB,SLG,SNA,SNPS,SO,SPG,SPGI,SRE,STE,STT,STX,STZ,SWK,SWKS,SYF,SYK,SYY,T,TAP,TDG,TDY,TEL,TFC,TFX,TGT,TIF,TJX,TMO,TMUS,TPR,TROW,TRV,TSCO,TSN,TT,TTWO,TWTR,TXN,TXT,TYL,UA,UAA,UAL,UDR,UHS,ULTA,UNH,UNM,UNP,UPS,URI,USB,V,VAR,VFC,VIAC,VLO,VMC,VNO,VRSK,VRSN,VRTX,VTR,VZ,WAB,WAT,WBA,WDC,WEC,WELL,WFC,WHR,WLTW,WM,WMB,WMT,WRB,WRK,WST,WU,WY,WYNN,XEL,XLNX,XOM,XRAY,XRX,XYL',
 'YUM,ZBH,ZBRA,ZION,ZTS']

In [10]:
symbol_strings = ['A,AAL,AAP,AAPL,ABBV,ABC,ABMD,ABT,ACN,ADBE,ADI,ADM,ADP,ADSK,AEE,AEP,AES,AFL,AIG,AIV,AIZ,AJG,AKAM,ALB,ALGN,ALK,ALL,ALLE,ALXN,AMAT,AMCR,AMD,AME,AMGN,AMP,AMT,AMZN,ANET,ANSS,ANTM,AON,AOS,APA,APD,APH,APTV,ARE,ATO,ATVI,AVB,AVGO,AVY,AWK,AXP,AZO,BA,BAC,BAX,BBY,BDX,BEN,BF.B,BIIB,BIO,BK,BKNG,BKR,BLK,BLL,BMY,BR,BRK.B,BSX,BWA,BXP,C,CAG,CAH,CARR,CAT,CB,CBOE,CBRE,CCI,CCL,CDNS,CDW,CE,CERN,CF,CFG,CHD,CHRW,CHTR,CI,CINF,CL,CLX,CMA,CMCSA',
 'CME,CMG,CMI,CMS,CNC,CNP,COF,COG,COO,COP,COST,COTY,CPB,CPRT,CRM,CSCO,CSX,CTAS,CTL,CTSH,CTVA,CTXS,CVS,CVX,CXO,D,DAL,DD,DE,DFS,DG,DGX,DHI,DHR,DIS,DISCK,DISH,DLR,DLTR,DOV,DOW,DPZ,DRE,DRI,DTE,DUK,DVA,DVN,DXC,DXCM,EA,EBAY,ECL,ED,EFX,EIX,EL,EMN,EMR,EOG,EQIX,EQR,ES,ESS,ETFC,ETN,ETR,EVRG,EW,EXC,EXPD,EXPE,EXR,F,FANG,FAST,FB,FBHS,FCX,FDX,FE,FFIV,FIS,FISV,FITB,FLIR,FLS,FLT,FMC,FOX,FOXA,FRC,FRT,FTI,FTNT,FTV,GD,GE,GILD',
 'GIS,GL,GLW,GM,GOOG,GOOGL,GPC,GPN,GPS,GRMN,GS,GWW,HAL,HAS,HBAN,HBI,HCA,HD,HES,HIG,HII,HLT,HOLX,HON,HPE,HPQ,HRB,HRL,HSIC,HST,HSY,HUM,HWM,IBM,ICE,IDXX,IEX,IFF,ILMN,INCY,INFO,INTC,INTU,IP,IPG,IPGP,IQV,IR,IRM,ISRG,IT,ITW,IVZ,J,JBHT,JCI,JKHY,JNJ,JNPR,JPM,K,KEY,KEYS,KHC,KIM,KLAC,KMB,KMI,KMX,KO,KR,KSS,KSU,L,LB,LDOS,LEG,LEN,LH,LHX,LIN,LKQ,LLY,LMT,LNC,LNT,LOW,LRCX,LUV,LVS,LW,LYB,LYV,MA,MAA,MAR,MAS,MCD,MCHP',
 'MCK,MCO,MDLZ,MDT,MET,MGM,MHK,MKC,MKTX,MLM,MMC,MMM,MNST,MO,MOS,MPC,MRK,MRO,MS,MSCI,MSFT,MSI,MTB,MTD,MU,MXIM,MYL,NBL,NCLH,NDAQ,NEE,NEM,NFLX,NI,NKE,NLOK,NLSN,NOC,NOV,NOW,NRG,NSC,NTAP,NTRS,NUE,NVDA,NVR,NWL,NWS,NWSA,O,ODFL,OKE,OMC,ORCL,ORLY,OTIS,OXY,PAYC,PAYX,PBCT,PCAR,PEAK,PEG,PEP,PFE,PFG,PG,PGR,PH,PHM,PKG,PKI,PLD,PM,PNC,PNR,PNW,PPG,PPL,PRGO,PRU,PSA,PSX,PVH,PWR,PXD,PYPL,QCOM,QRVO,RCL,RE,REG,REGN,RF,RHI,RJF,RL,RMD,ROK',
 'ROL,ROP,ROST,RSG,RTX,SBAC,SBUX,SCHW,SEE,SHW,SIVB,SJM,SLB,SLG,SNA,SNPS,SO,SPG,SPGI,SRE,STE,STT,STX,STZ,SWK,SWKS,SYF,SYK,SYY,T,TAP,TDG,TDY,TEL,TFC,TFX,TGT,TIF,TJX,TMO,TMUS,TPR,TROW,TRV,TSCO,TSN,TT,TTWO,TWTR,TXN,TXT,TYL,UA,UAA,UAL,UDR,UHS,ULTA,UNH,UNM,UNP,UPS,URI,USB,V,VAR,VFC,VLO,VMC,VNO,VRSK,VRSN,VRTX,VTR,VZ,WAB,WAT,WBA,WDC,WEC,WELL,WFC,WHR,WM,WMB,WMT,WRB,WRK,WST,WU,WY,WYNN,XEL,XLNX,XOM,XRAY,XRX,XYL',
 'YUM,ZBH,ZBRA,ZION,ZTS']

Now we need to create a blank DataFrame and add our data to the data frame one by one

In [11]:
final_dataframe = pd.DataFrame(columns = my_columns)

for symbol_string in symbol_strings:
#     print(symbol_strings)
    batch_api_call_url = f'https://sandbox.iexapis.com/stable/stock/market/batch/?types=stats,quote&symbols={symbol_string}&token={IEX_CLOUD_API_TOKEN}'
    data = requests.get(batch_api_call_url).json()
    for symbol in symbol_string.split(','):
        final_dataframe = final_dataframe.append(
                                        pd.Series([symbol, 
                                                   data[symbol]['quote']['latestPrice'],
                                                   data[symbol]['stats']['year1ChangePercent'],
                                                   'N/A'
                                                   ], 
                                                  index = my_columns), 
                                        ignore_index = True)
        
    
final_dataframe

    Ticker    Price One-Year Price Return Number of Shares to Buy
0        A  124.570             -0.231828                     N/A
1      AAL   12.554             -0.425953                     N/A
2      AAP  163.170             -0.251662                     N/A
3     AAPL  143.670              0.003295                     N/A
4     ABBV  140.447               0.36943                     N/A
..     ...      ...                   ...                     ...
496    YUM  111.170             -0.114159                     N/A
497    ZBH  108.380             -0.282329                     N/A
498   ZBRA  271.540             -0.510848                     N/A
499   ZION   52.650             -0.173203                     N/A
500    ZTS  152.440             -0.221222                     N/A

[501 rows x 4 columns]

<h4>Removing Low-Momentum Stocks</h4>
The investment strategy that we are building seeks to identify the 50 highest-momentum stocks in the S&P500. <br>
Beacuase of this, we need remove all the stocks in the Data Frame that fall below this momentum threshold. We'll sort the DataFrame by the Stocks ne-year price return and drop all stocks outside the top 50.

In [12]:
final_dataframe.sort_values('One-Year Price Return', ascending = False, inplace = True)
final_dataframe = final_dataframe[:51]
final_dataframe.reset_index(drop = True, inplace = True)
final_dataframe

   Ticker     Price One-Year Price Return Number of Shares to Buy
0      LB    81.540               2.30365                     N/A
1     OXY    64.510                1.0865                     N/A
2     DVN    63.880              0.804659                     N/A
3     HRB    44.760               0.80335                     N/A
4      CF   102.220              0.759993                     N/A
5     MRO    22.972               0.69166                     N/A
6     APA    35.436              0.689789                     N/A
7     MCK   356.500              0.682359                     N/A
8     MPC   102.080              0.645539                     N/A
9    VRTX   302.630              0.635512                     N/A
10    UNM    40.500              0.627879                     N/A
11    COP   107.590              0.598768                     N/A
12    VAR   179.700              0.595842                     N/A
13    VLO   112.851              0.595262                     N/A
14    XOM    88.800              0.548109                     N/A
15    KSU   301.660              0.515264                     N/A
16    EOG   118.140              0.495027                     N/A
17    CVX   145.280               0.46078                     N/A
18    LLY   337.441              0.456471                     N/A
19   NLSN    28.768              0.448797                     N/A
20    HES   112.050              0.429966                     N/A
21    PXD   222.390              0.408802                     N/A
22     CI   292.890              0.397337                     N/A
23    CAH    70.680              0.376444                     N/A
24   DLTR   142.252               0.37273                     N/A
25   ABBV   140.447               0.36943                     N/A
26    ADM    81.985              0.357112                     N/A
27    WRB    68.270              0.355785                     N/A
28   CTVA    58.160              0.354324                     N/A
29    MOS    50.704              0.345683                     N/A
30    COG    22.540              0.345136                     N/A
31    HSY   226.900              0.341677                     N/A
32    PGR   118.210              0.338951                     N/A
33   ANET   119.200              0.335183                     N/A
34    GIS    79.600              0.324195                     N/A
35    NOC   475.550              0.318052                     N/A
36    UNH   537.160              0.300679                     N/A
37   FANG   125.980              0.300298                     N/A
38     LW    80.280               0.29299                     N/A
39   ANTM   495.710              0.282711                     N/A
40    HUM   503.799              0.254599                     N/A
41    AZO  2165.820               0.25404                     N/A
42    CNC    79.430              0.239322                     N/A
43    GPC   158.170              0.237576                     N/A
44     ED    87.979              0.237057                     N/A
45    SRE   150.120              0.236341                     N/A
46    GWW   515.170              0.231531                     N/A
47    ALB   272.810              0.228298                     N/A
48    BMY    73.700              0.226753                     N/A
49   INFO   112.010              0.219701                     N/A
50    PSX    84.197              0.206522                     N/A

<h4> Calculating the number of Shares to Buy</h4>
Just like the last project, we now need to calculate the number of shares to buy. The one change we're going to make is wrapping this functionality inside a function, since we'll be using it again later in this Notebook

In [13]:
def portfolio_input():
    global portfolio_size
    portfolio_size = input("Enter the value of your portfolio:")

    try:
        val=float(portfolio_size)
    except ValueError:
        print("That's not a number! \n Try again:")
        portfolio_size = input("Enter the value of your portfolio:")

portfolio_input()
print(portfolio_size)

10000000

In [14]:
position_size = float(portfolio_size) / len(final_dataframe.index)
for i in range(0, len(final_dataframe['Ticker'])):
    final_dataframe.loc[i, 'Number of Shares to Buy'] = math.floor(position_size / final_dataframe['Price'][i])
final_dataframe

c:\Users\gustavo.j.siebel\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

   Ticker     Price One-Year Price Return Number of Shares to Buy
0      LB    81.540               2.30365                    2404
1     OXY    64.510                1.0865                    3039
2     DVN    63.880              0.804659                    3069
3     HRB    44.760               0.80335                    4380
4      CF   102.220              0.759993                    1918
5     MRO    22.972               0.69166                    8535
6     APA    35.436              0.689789                    5533
7     MCK   356.500              0.682359                     550
8     MPC   102.080              0.645539                    1920
9    VRTX   302.630              0.635512                     647
10    UNM    40.500              0.627879                    4841
11    COP   107.590              0.598768                    1822
12    VAR   179.700              0.595842                    1091
13    VLO   112.851              0.595262                    1737
14    XOM    88.800              0.548109                    2208
15    KSU   301.660              0.515264                     649
16    EOG   118.140              0.495027                    1659
17    CVX   145.280               0.46078                    1349
18    LLY   337.441              0.456471                     581
19   NLSN    28.768              0.448797                    6815
20    HES   112.050              0.429966                    1749
21    PXD   222.390              0.408802                     881
22     CI   292.890              0.397337                     669
23    CAH    70.680              0.376444                    2774
24   DLTR   142.252               0.37273                    1378
25   ABBV   140.447               0.36943                    1396
26    ADM    81.985              0.357112                    2391
27    WRB    68.270              0.355785                    2872
28   CTVA    58.160              0.354324                    3371
29    MOS    50.704              0.345683                    3867
30    COG    22.540              0.345136                    8699
31    HSY   226.900              0.341677                     864
32    PGR   118.210              0.338951                    1658
33   ANET   119.200              0.335183                    1644
34    GIS    79.600              0.324195                    2463
35    NOC   475.550              0.318052                     412
36    UNH   537.160              0.300679                     365
37   FANG   125.980              0.300298                    1556
38     LW    80.280               0.29299                    2442
39   ANTM   495.710              0.282711                     395
40    HUM   503.799              0.254599                     389
41    AZO  2165.820               0.25404                      90
42    CNC    79.430              0.239322                    2468
43    GPC   158.170              0.237576                    1239
44     ED    87.979              0.237057                    2228
45    SRE   150.120              0.236341                    1306
46    GWW   515.170              0.231531                     380
47    ALB   272.810              0.228298                     718
48    BMY    73.700              0.226753                    2660
49   INFO   112.010              0.219701                    1750
50    PSX    84.197              0.206522                    2328

<h4> Momentum Strategy Melhor e mais Realista</h4>

Empresas de investimento quantitativo reais diferenciam momentum stocks em "high quality" e "low quality";

- High-quality mostram um crescimento menor e mais estável ao longo do período de tempo
- Low-quality podem não mostrar momentum ao longo do tempo, e depois subir.

A razão pela qual foi selecionada high-quality é por que low-quality momentum pode ser usada por notícias de curto prazo que são improváveis de serem repetidas no futuro.

Para identificar high-quality momentum, é preciso construir uma estratégia que selecione ações com os maiores percentuais de:

1. 1 mês de retorno/preço
2. 3 mês de retorno/preço
3. 6 mês de retorno/preço
4. 1 ano de retorno/preço

In [19]:
hqm_columns = [
                'Ticker', 
                'Price', 
                'Number of Shares to Buy', 
                'One-Year Price Return', 
                'One-Year Return Percentile',
                'Six-Month Price Return',
                'Six-Month Return Percentile',
                'Three-Month Price Return',
                'Three-Month Return Percentile',
                'One-Month Price Return',
                'One-Month Return Percentile',
                'HQM Score'
                ]

hqm_dataframe = pd.DataFrame(columns = hqm_columns)

for symbol_string in symbol_strings:
#     print(symbol_strings)
    batch_api_call_url = f'https://sandbox.iexapis.com/stable/stock/market/batch/?types=stats,quote&symbols={symbol_string}&token={IEX_CLOUD_API_TOKEN}'
    data = requests.get(batch_api_call_url).json()
    for symbol in symbol_string.split(','):
        hqm_dataframe = hqm_dataframe.append(
                                        pd.Series([symbol, 
                                                   data[symbol]['quote']['latestPrice'],
                                                   'N/A',
                                                   data[symbol]['stats']['year1ChangePercent'],
                                                   'N/A',
                                                   data[symbol]['stats']['month6ChangePercent'],
                                                   'N/A',
                                                   data[symbol]['stats']['month3ChangePercent'],
                                                   'N/A',
                                                   data[symbol]['stats']['month1ChangePercent'],
                                                   'N/A',
                                                   'N/A'
                                                   ], 
                                                  index = hqm_columns), 
                                        ignore_index = True)
        
hqm_dataframe.columns

Index(['Ticker', 'Price', 'Number of Shares to Buy', 'One-Year Price Return',
       'One-Year Return Percentile', 'Six-Month Price Return',
       'Six-Month Return Percentile', 'Three-Month Price Return',
       'Three-Month Return Percentile', 'One-Month Price Return',
       'One-Month Return Percentile', 'HQM Score'],
      dtype='object')

<h4> Calculo do Percentual dos Momentos</h4>

Precisamos saber calcular o percentual de momentum de cada ação no mercado. Mais espeificamente, precisamos calcular o score percentual de cada metrica descrita anteriormente.  1 mês de retorno/preço, 3 mês de retorno/preço, 6 mês de retorno/preço e 1 ano de retorno/preço.

In [37]:
#Limpando os valores nulos
mask = hqm_dataframe['One-Year Price Return'].isnull() \
            | hqm_dataframe['Six-Month Price Return'].isnull() \
            | hqm_dataframe['Three-Month Price Return'].isnull() \
            | hqm_dataframe['One-Month Price Return'].isnull()


hqm_dataframe = hqm_dataframe.drop([118, 164, 324, 325])
hqm_dataframe[mask]

C:\Users\GUSTAV~1.SIE\AppData\Local\Temp/ipykernel_34748/732311587.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  hqm_dataframe[mask]

Empty DataFrame
Columns: [Ticker, Price, Number of Shares to Buy, One-Year Price Return, One-Year Return Percentile, Six-Month Price Return, Six-Month Return Percentile, Three-Month Price Return, Three-Month Return Percentile, One-Month Price Return, One-Month Return Percentile, HQM Score]
Index: []

In [38]:
time_periods = [
                'One-Year',
                'Six-Month',
                'Three-Month',
                'One-Month'
                ]

for row in hqm_dataframe.index:
    for time_period in time_periods:
        hqm_dataframe.loc[row, f'{time_period} Return Percentile'] = stats.percentileofscore(hqm_dataframe[f'{time_period} Price Return'], hqm_dataframe.loc[row, f'{time_period} Price Return'])#/100

# Print each percentile score to make sure it was calculated properly
for time_period in time_periods:
    print(hqm_dataframe[f'{time_period} Return Percentile'])

#Print the entire DataFrame    
hqm_dataframe

0      34.808853
1       9.054326
2      32.394366
3      74.044266
4      94.969819
         ...
496    55.130785
497    26.961771
498     3.822938
499    46.277666
500    37.022133
Name: One-Year Return Percentile, Length: 497, dtype: object
0      68.410463
1      15.895372
2       37.22334
3       48.89336
4      70.422535
         ...
496    67.806841
497    53.521127
498     6.841046
499    38.028169
500    45.472837
Name: Six-Month Return Percentile, Length: 497, dtype: object
0      81.086519
1      44.869215
2      32.394366
3      75.251509
4      41.851107
         ...
496    47.484909
497     70.82495
498    24.346076
499    67.404427
500    18.511066
Name: Three-Month Return Percentile, Length: 497, dtype: object
0      82.092555
1      51.911469
2      75.050302
3      37.424547
4      98.189135
         ...
496    81.287726
497     91.95171
498    21.730382
499    67.203219
500    80.684105
Name: One-Month Return Percentile, Length: 497, dtype: object

,Ticker,Price,Number of Shares to Buy,One-Year Price Return,One-Year Return Percentile,Six-Month Price Return,Six-Month Return Percentile,Three-Month Price Return,Three-Month Return Percentile,One-Month Price Return,One-Month Return Percentile,HQM Score
0,A,124.520,N/A,-0.236529,34.808853,-0.115382,68.410463,0.04391,81.086519,-0.043076,82.092555,N/A
1,AAL,12.472,N/A,-0.431366,9.054326,-0.34071,15.895372,-0.061025,44.869215,-0.094976,51.911469,N/A
2,AAP,162.850,N/A,-0.250437,32.394366,-0.25047,37.22334,-0.0888,32.394366,-0.057479,75.050302,N/A
3,AAPL,145.180,N/A,0.003207,74.044266,-0.202,48.89336,0.025136,75.251509,-0.117258,37.424547,N/A
4,ABBV,139.160,N/A,0.370552,94.969819,-0.105177,70.422535,-0.068095,41.851107,0.051761,98.189135,N/A
...,...,...,...,...,...,...,...,...,...,...,...,...
496,YUM,110.370,N/A,-0.11487,55.130785,-0.116244,67.806841,-0.054145,47.484909,-0.044783,81.287726,N/A
497,ZBH,110.650,N/A,-0.281834,26.961771,-0.176634,53.521127,0.009621,70.82495,-0.000854,91.95171,N/A
498,ZBRA,275.940,N/A,-0.519436,3.822938,-0.400915,6.841046,-0.113732,24.346076,-0.144319,21.730382,N/A
499,ZION,53.560,N/A,-0.171706,46.277666,-0.248144,38.028169,0.003477,67.404427,-0.073188,67.203219,N/A
500,ZTS,155.180,N/A,-0.223545,37.022133,-0.214777,45.472837,-0.135023,18.511066,-0.045581,80.684105,N/A

<h4>High Quality Momentum </h4>

Aplicando o score podemos filtrar as ações nesta estratégia<br>

In [39]:
from statistics import mean

for row in hqm_dataframe.index:
    momentum_percentiles = []
    for time_period in time_periods:
        momentum_percentiles.append(hqm_dataframe.loc[row, f'{time_period} Return Percentile'])
    hqm_dataframe.loc[row, 'HQM Score'] = mean(momentum_percentiles)

<h4>Filtro das 50 melhores ações</h4>
Foram identificadas 50 melhores ações por momentum.

In [40]:
hqm_dataframe.sort_values(by = 'HQM Score', ascending = False)
hqm_dataframe = hqm_dataframe[:51]

<h4>Quantas ações comprar;</h4>

In [41]:
portfolio_input()

In [42]:
position_size = float(portfolio_size) / len(hqm_dataframe.index)
for i in range(0, len(hqm_dataframe['Ticker'])-1):
    hqm_dataframe.loc[i, 'Number of Shares to Buy'] = math.floor(position_size / hqm_dataframe['Price'][i])
hqm_dataframe

c:\Users\gustavo.j.siebel\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

,Ticker,Price,Number of Shares to Buy,One-Year Price Return,One-Year Return Percentile,Six-Month Price Return,Six-Month Return Percentile,Three-Month Price Return,Three-Month Return Percentile,One-Month Price Return,One-Month Return Percentile,HQM Score
0,A,124.520,157,-0.236529,34.808853,-0.115382,68.410463,0.04391,81.086519,-0.043076,82.092555,66.599598
1,AAL,12.472,1572,-0.431366,9.054326,-0.34071,15.895372,-0.061025,44.869215,-0.094976,51.911469,30.432596
2,AAP,162.850,120,-0.250437,32.394366,-0.25047,37.22334,-0.0888,32.394366,-0.057479,75.050302,44.265594
3,AAPL,145.180,135,0.003207,74.044266,-0.202,48.89336,0.025136,75.251509,-0.117258,37.424547,58.903421
4,ABBV,139.160,140,0.370552,94.969819,-0.105177,70.422535,-0.068095,41.851107,0.051761,98.189135,76.358149
...,...,...,...,...,...,...,...,...,...,...,...,...
46,ARE,143.810,136,-0.274252,28.370221,-0.304179,22.937626,-0.034528,54.124748,-0.108222,44.668008,37.525151
47,ATO,106.090,184,0.202674,89.738431,-0.11358,69.014085,-0.051513,48.289738,-0.104038,47.887324,63.732394
48,ATVI,76.216,257,-0.027207,69.014085,-0.068602,77.665996,-0.040047,51.911469,-0.050459,78.873239,69.366197
49,AVB,188.763,103,-0.15286,48.89336,-0.28002,28.772636,-0.046157,49.899396,-0.094073,52.917505,45.120724
50,AVGO,465.910,N/A,-0.06337,64.386318,-0.292604,25.150905,-0.075254,38.631791,-0.119291,35.613682,40.945674

<h4> passando para excel</h4>

In [43]:
writer = pd.ExcelWriter('momentum_strategy.xlsx', engine='xlsxwriter')
hqm_dataframe.to_excel(writer, sheet_name='Momentum Strategy', index = False)

In [44]:
background_color = '#0a0a23'
font_color = '#ffffff'

string_template = writer.book.add_format(
        {
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

dollar_template = writer.book.add_format(
        {
            'num_format':'$0.00',
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

integer_template = writer.book.add_format(
        {
            'num_format':'0',
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

percent_template = writer.book.add_format(
        {
            'num_format':'0.0%',
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

In [45]:
column_formats = { 
                    'A': ['Ticker', string_template],
                    'B': ['Price', dollar_template],
                    'C': ['Number of Shares to Buy', integer_template],
                    'D': ['One-Year Price Return', percent_template],
                    'E': ['One-Year Return Percentile', percent_template],
                    'F': ['Six-Month Price Return', percent_template],
                    'G': ['Six-Month Return Percentile', percent_template],
                    'H': ['Three-Month Price Return', percent_template],
                    'I': ['Three-Month Return Percentile', percent_template],
                    'J': ['One-Month Price Return', percent_template],
                    'K': ['One-Month Return Percentile', percent_template],
                    'L': ['HQM Score', integer_template]
                    }

for column in column_formats.keys():
    writer.sheets['Momentum Strategy'].set_column(f'{column}:{column}', 20, column_formats[column][1])
    writer.sheets['Momentum Strategy'].write(f'{column}1', column_formats[column][0], string_template)

In [46]:
writer.save()

### PROJECT 03 - Quantitative Value Investing Strategy Screener

<h3> Value Investing Project Overview</h3>
Value investing means investing in stocks that are trading below their perceived intrinsic value.<br>
Value investing was popularized by investors like Waren Buffet, seth Klarman, and  Benjamin Graham.<br></br>
Creating algorithmic value investing srtategies relies on a concept called <font color=red>multiples</font>.<br> 
Multiples are simply a way that investors use to estimate how valuable a company is.<br>
Multiples are calculated by dividing a company's stock price by sme measure of company's worth like earnings or assets.

Examples of <font color=red>multiples</font> used in value investing:

- Price-to-earnings
- Price-to-book-value
- Price-to-free-cash-flow

Each of the individual multilpes used by value investors has its pros and cons. <br>
One way to minimize the impact of any specific multiples is by using a <font color=red>composite</font>.<br></br>
Composite is just a average of many different valuation strategies. <br>
We'll use  composite of 5 different value investing metrics.